const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = {num: v => Number(v) || 0, esMassPasillo10: v => String(v).toUpperCase().startsWith('MASS-10-')};
vm.createContext(context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../modules/operaciones-independiente/js/rotacion.js'),'utf8'),context);
const products = [{CODIGO:'001',CODIGO_ALT:'A1',UXB:100},{CODIGO:'002',UXB:1},{CODIGO:'003',UXB:1}];
const source = [{Codigo:'001',UNIDADES:800},{Codigo:'A1',UNIDADES:200},{Codigo:'002',UNIDADES:80},{Codigo:'003',UNIDADES:10},{Codigo:'004',UNIDADES:50}];
const inv = [{PRODUCTO:'001',UNACT:20,UBICACION:'Mass-01-01'}, {PRODUCTO:'001',UNACT:99,UBICACION:'Mass-10-01'}, {PRODUCTO:'EXTRA',UNACT:8,UBICACION:'Mass-01-02'}];
const locations = [{Producto:"'001",Mascara:'Mass-01-01','Tipo Ubicac':'Permanente'},{Producto:'001',Mascara:'Mass-01-02','Tipo Ubicac':'Dinamico'},{Producto:'002',Mascara:'Mass-10-01'}];
const rows = context.calcularRotacion(source,products,inv,locations,80,95,[{CODIGO:'002'}]);
assert.equal(rows.length,4);
assert.equal(rows[0].codigo,'002');
assert.equal(rows[0].categoria,'ALTA');
assert.equal(rows[0].shipTo,true);
assert.equal(rows[0].seteadas.size,0);
const one = rows.find(r => r.codigo === '001');
assert.equal(one.unidades,1000); assert.equal(one.bultos,10); assert.equal(one.stock,20);
assert.equal(one.seteadas.size,2); assert.equal(one.tipos.get('Mass-01-01'),'Permanente');
assert.equal(rows.find(r=>r.codigo==='004').categoria,'SIN UXB');
const units = context.calcularRotacion(source,products,inv,locations,80,95,[],'unidades');
assert.equal(units[0].codigo,'001');
assert.equal(units[0].categoria,'ALTA');
assert.equal(context.calcularRotacion([],products,inv,locations).length,0);
context.document = {getElementById: () => ({textContent:''})};
context.descargarExcelHojas = (nombre,hojas) => {
  assert.equal(nombre,'rotacion');
  assert.equal(hojas[0].filas.length,2);
  assert.equal(hojas[0].filas[1][0],'002');
  assert.equal(hojas[0].filas[1][13],'SI');
  assert.equal(hojas[0].filas[1][14],'NO REQUIERE UBICACION - SHIP TO');
  assert.equal(hojas[1].nombre,'Criterio');
};
context.resultado = rows[0];
vm.runInContext('rotacionVisibles = [resultado]; exportarRotacion();',context);
console.log('OK: conversion, agrupacion, alias, Ship To, tipos, ABC y exclusiones');
